/**
 * Teacher-facing attendance marking interface.
 */
import React, { useState, useEffect, useReducer } from 'react';
import api from '../../services/api';
import { getApiErrorMessage } from '../../services/apiError';
import '../../styles/Attendance.css';

const STATUSES=[{key:'present',label:'P',title:'Present'},{key:'absent',label:'A',title:'Absent'},{key:'late',label:'L',title:'Late'},{key:'excused',label:'E',title:'Excused'}];
const STATUS_KEY={present:'P',absent:'A',late:'L',excused:'E'};
function recordsReducer(state,action){switch(action.type){case'INIT':return Object.fromEntries(action.records.map(r=>[r.student,{status:r.status,remark:r.remark||''}]));case'SET_STATUS':return{...state,[action.studentId]:{...state[action.studentId],status:action.status}};case'SET_REMARK':return{...state,[action.studentId]:{...state[action.studentId],remark:action.remark}};case'MARK_ALL_PRESENT':return Object.fromEntries(Object.keys(state).map(sid=>[sid,{status:'present',remark:''}]));default:return state;}}

export default function TakeAttendance(){
 const[terms,setTerms]=useState([]),[classArms,setClassArms]=useState([]),[periods,setPeriods]=useState([]),[schoolMode,setSchoolMode]=useState('daily');
 const[selectedTerm,setSelectedTerm]=useState(''),[selectedClassArm,setSelectedClassArm]=useState(''),[selectedDate,setSelectedDate]=useState(()=>new Date().toISOString().split('T')[0]),[selectedPeriod,setSelectedPeriod]=useState('');
 const[session,setSession]=useState(null),[students,setStudents]=useState([]),[records,dispatch]=useReducer(recordsReducer,{});const[loading,setLoading]=useState(false),[submitting,setSubmitting]=useState(false),[finalizing,setFinalizing]=useState(false),[error,setError]=useState(null),[success,setSuccess]=useState(null);
 useEffect(()=>{let active=true;Promise.all([api.get('/api/terms/'),api.get('/api/class-arms/'),api.get('/api/timetable/periods/'),api.get('/api/school/me/')]).then(([t,c,p,s])=>{if(!active)return;const list=t.data.results??t.data;setTerms(list);setClassArms(c.data.results??c.data);setPeriods(p.data.results??p.data);setSchoolMode(s.data?.attendance_mode??'daily');const current=list.find(x=>x.is_current);if(current)setSelectedTerm(String(current.id));}).catch(err=>active&&setError(getApiErrorMessage(err,'Unable to load attendance setup.')));return()=>{active=false;};},[]);
 function loadSession(data){setSession(data);const rows=data.records||[];setStudents(rows.map(r=>({id:r.student,name:r.student_name,admission_number:r.admission_number})));dispatch({type:'INIT',records:rows});}
 async function loadExistingSession({class_arm,term,date,period}){try{const q=new URLSearchParams({class_arm:String(class_arm),term:String(term),date});if(period)q.set('period',String(period));const{data}=await api.get(`/api/attendance/sessions/?${q}`);const list=data.results??data;if(!list.length){setError('Existing session could not be found.');return;}const detail=await api.get(`/api/attendance/sessions/${list[0].id}/`);loadSession(detail.data);}catch(err){setError(getApiErrorMessage(err,'Failed to load existing session.'));}}
 async function handleStartSession(){if(!selectedTerm||!selectedClassArm){setError('Please select a term and class before starting.');return;}setLoading(true);setError(null);setSuccess(null);const body={class_arm:Number(selectedClassArm),term:Number(selectedTerm),date:selectedDate,mode:schoolMode,...(schoolMode==='per_period'&&selectedPeriod?{period:Number(selectedPeriod)}:{})};try{const{data}=await api.post('/api/attendance/sessions/start/',body);loadSession(data);}catch(err){const detail=err?.response?.data?.detail??'';if(detail.includes('already exists')){setError('A session already exists for this slot. Loading it now…');await loadExistingSession(body);}else setError(getApiErrorMessage(err,'Failed to start session.'));}finally{setLoading(false);}}
 async function submit(){if(!session)return;setSubmitting(true);setError(null);try{const payload={records:Object.entries(records).map(([student_id,r])=>({student_id:Number(student_id),...r}))};const{data}=await api.patch(`/api/attendance/sessions/${session.id}/submit/`,payload);loadSession(data);setSuccess('Attendance saved successfully.');}catch(err){setError(getApiErrorMessage(err,'Failed to save attendance.'));}finally{setSubmitting(false);}}
 async function finalize(){if(!session)return;setFinalizing(true);setError(null);try{await api.patch(`/api/attendance/sessions/${session.id}/finalize/`);setSession(s=>({...s,is_finalized:true}));setSuccess('Register locked successfully.');}catch(err){setError(getApiErrorMessage(err,'Failed to lock register.'));}finally{setFinalizing(false);}}
 return <div className="att-page"><div className="att-header"><h1 className="att-header__title">Take Attendance<span className="att-header__sub">Mark and manage your assigned class register</span></h1></div>{error&&<div className="att-alert att-alert--error" role="alert">⚠ {error}</div>}{success&&<div className="att-alert att-alert--info">✓ {success}</div>}<div className="att-card"><div className="att-card__body"><div style={{display:'flex',gap:12,flexWrap:'wrap'}}><select className="att-select" value={selectedTerm} onChange={e=>setSelectedTerm(e.target.value)}><option value="">— Term —</option>{terms.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select><select className="att-select" value={selectedClassArm} onChange={e=>{setSelectedClassArm(e.target.value);setSession(null);}}><option value="">— Class —</option>{classArms.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select><input type="date" value={selectedDate} onChange={e=>setSelectedDate(e.target.value)}/>{schoolMode==='per_period'&&<select className="att-select" value={selectedPeriod} onChange={e=>setSelectedPeriod(e.target.value)}><option value="">— Period —</option>{periods.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select>}<button onClick={handleStartSession} disabled={loading}>{loading?'Loading…':'Start / Resume'}</button></div></div></div>{session&&<div className="att-card"><div className="att-card__body"><button onClick={()=>dispatch({type:'MARK_ALL_PRESENT'})} disabled={session.is_finalized}>Mark All Present</button>{students.map(stu=><div key={stu.id} style={{display:'grid',gridTemplateColumns:'1fr auto 1fr',gap:12,alignItems:'center',padding:'10px 0'}}><strong>{stu.name}</strong><div>{STATUSES.map(s=><button key={s.key} title={s.title} disabled={session.is_finalized} onClick={()=>dispatch({type:'SET_STATUS',studentId:stu.id,status:s.key})} style={{fontWeight:records[stu.id]?.status===s.key?800:400}}>{STATUS_KEY[s.key]}</button>)}</div><input value={records[stu.id]?.remark||''} disabled={session.is_finalized} placeholder="Remark" onChange={e=>dispatch({type:'SET_REMARK',studentId:stu.id,remark:e.target.value})}/></div>)}<div style={{display:'flex',gap:10}}><button onClick={submit} disabled={submitting||session.is_finalized}>{submitting?'Saving…':'Save Attendance'}</button><button onClick={finalize} disabled={finalizing||session.is_finalized}>{session.is_finalized?'Register Locked':finalizing?'Locking…':'Lock Register'}</button></div></div></div>}</div>;
}
