# Generated by Django 4.2.16 on 2026-09-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_platformsecurity_platformevent'),
        ('accounts', '0003_parentstudentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParentLoginChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('code_hash', models.CharField(max_length=128)),
                ('expires_at', models.DateTimeField()),
                ('requested_at', models.DateTimeField()),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed', models.BooleanField(default=False)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
            ],
        ),
        migrations.AddConstraint(
            model_name='parentloginchallenge',
            constraint=models.UniqueConstraint(fields=('school', 'phone'), name='unique_parent_challenge'),
        ),
    ]
