# Generated by Django 4.2.16 on 2026-09-22 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_parentloginchallenge_and_more'),
    ]

    operations = [
        # Existing addresses and uniqueness are preserved. Before reversing this
        # migration, resolve any newly created NULL emails without deleting users.
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email address'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.CheckConstraint(check=models.Q(('role', 'student'), ('email__isnull', False), _connector='OR'), name='nonstudent_email_required'),
        ),
    ]
