# Generated by Django 4.2.16 on 2026-09-14 17:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0002_school_approval_status_school_platform_notes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformSecurity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.CharField(choices=[('owner', 'Owner'), ('viewer', 'Read only')], default='owner', max_length=12)),
                ('encrypted_secret', models.TextField(blank=True)),
                ('enabled', models.BooleanField(default=False)),
                ('last_step', models.BigIntegerField(default=-1)),
                ('recovery_hashes', models.JSONField(default=list)),
                ('session_version', models.PositiveIntegerField(default=1)),
                ('challenge_nonce', models.CharField(blank=True, max_length=64)),
                ('failures', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='platform_security', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlatformEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actor_email', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(max_length=100)),
                ('target', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
