# Generated by Django 4.2.16 on 2026-09-23 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_demorequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='subscription_plan',
            field=models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='free', max_length=20),
        ),
    ]
