# Generated by Django 4.2.16 on 2026-09-20 05:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_redact_legacy_auth_messages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationoutbox',
            name='log',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='outbox', to='notifications.notificationlog'),
        ),
    ]
