# Generated by Django 5.2.17 on 2026-09-27 18:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationoutbox_log'),
        ('tenants', '0005_alter_school_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Communication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(max_length=300)),
                ('title', models.CharField(max_length=160)),
                ('body', models.TextField()),
                ('audience', models.CharField(max_length=32)),
                ('audience_label', models.CharField(max_length=160)),
                ('recipient_count', models.PositiveIntegerField()),
                ('key', models.CharField(max_length=64)),
                ('digest', models.CharField(max_length=64)),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CommunicationRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_name', models.CharField(max_length=300)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='notifications.communication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portal_notices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='communication',
            index=models.Index(fields=['school', '-published_at'], name='notificatio_school__d3b53c_idx'),
        ),
        migrations.AddConstraint(
            model_name='communication',
            constraint=models.UniqueConstraint(fields=('school', 'key'), name='unique_communication_key'),
        ),
        migrations.AddIndex(
            model_name='communicationrecipient',
            index=models.Index(fields=['user', '-id'], name='notificatio_user_id_8ed172_idx'),
        ),
        migrations.AddConstraint(
            model_name='communicationrecipient',
            constraint=models.UniqueConstraint(fields=('communication', 'user'), name='unique_communication_recipient'),
        ),
    ]
