# Generated by Django 5.1.7 on 2026-03-23 10:39

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_term_next_term_begins'),
        ('enrollment', '0004_alter_classarm_options_alter_classlevel_options_and_more'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AffectiveDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punctuality', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('neatness', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('honesty', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('attentiveness', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('relationship_with_others', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('leadership', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('creativity', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('sport_games', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('handling_of_tools', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affective_domains', to='enrollment.classarm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affective_domains', to='tenants.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='affective_domains', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='affective_domains', to='academics.term')),
            ],
            options={
                'verbose_name': 'Affective Domain',
                'unique_together': {('student', 'term', 'school')},
            },
        ),
        migrations.CreateModel(
            name='GradeScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_score', models.DecimalField(decimal_places=2, max_digits=5)),
                ('grade', models.CharField(choices=[('A1', 'A1'), ('B2', 'B2'), ('B3', 'B3'), ('C4', 'C4'), ('C5', 'C5'), ('C6', 'C6'), ('D7', 'D7'), ('E8', 'E8'), ('F9', 'F9')], max_length=2)),
                ('remark', models.CharField(choices=[('Excellent', 'Excellent'), ('Very Good', 'Very Good'), ('Good', 'Good'), ('Credit', 'Credit'), ('Pass', 'Pass'), ('Fail', 'Fail')], max_length=20)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grade_scales', to='tenants.school')),
            ],
            options={
                'verbose_name': 'Grade Scale',
                'ordering': ['-min_score'],
                'unique_together': {('school', 'grade')},
            },
        ),
        migrations.CreateModel(
            name='PsychomotorDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handwriting', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('drawing', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('verbal_fluency', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('musical_skills', models.IntegerField(default=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_domains', to='enrollment.classarm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_domains', to='tenants.school')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_domains', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='psychomotor_domains', to='academics.term')),
            ],
            options={
                'verbose_name': 'Psychomotor Domain',
                'unique_together': {('student', 'term', 'school')},
            },
        ),
        migrations.CreateModel(
            name='ScoreEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_test', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('second_test', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('assignment', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('project', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('practical', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('ca_total', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('exam_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0'))])),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=5)),
                ('grade', models.CharField(blank=True, default='', max_length=2)),
                ('remark', models.CharField(blank=True, default='', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_entries', to='enrollment.classarm')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_entries', to='tenants.school')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_entries', to='academics.academicsession')),
                ('student', models.ForeignKey(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='score_entries', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_entries', to='enrollment.subject')),
                ('teacher', models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_entries', to=settings.AUTH_USER_MODEL)),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='score_entries', to='academics.term')),
            ],
            options={
                'verbose_name': 'Score Entry',
                'verbose_name_plural': 'Score Entries',
                'ordering': ['student__last_name', 'student__first_name'],
                'unique_together': {('student', 'subject', 'term', 'session', 'school')},
            },
        ),
    ]
