# Generated by Django 4.2.16 on 2026-09-25 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_term_next_term_begins'),
        ('tenants', '0005_alter_school_subscription_plan'),
        ('gradebook', '0002_decimal_grade_boundaries'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreentry',
            name='component_scores',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='review_state',
            field=models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=12),
        ),
        migrations.CreateModel(
            name='TermScoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('components', models.JSONField(default=list)),
                ('bands', models.JSONField(default=list)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('term', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='scoring', to='academics.term')),
            ],
        ),
        migrations.AddField(
            model_name='scoreentry',
            name='policy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='gradebook.termscoring'),
        ),
    ]
