# Generated by Django 5.2.17 on 2026-09-28 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gradebook', '0003_term_scoring_and_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreentry',
            name='component_sources',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
