# Generated by Django 4.2.16 on 2026-05-11 10:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('enrollment', '0004_alter_classarm_options_alter_classlevel_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_alter_term_next_term_begins'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('promoted', 'Promoted'), ('repeated', 'Repeated'), ('graduated', 'Graduated'), ('withdrawn', 'Withdrawn')], max_length=20)),
                ('criteria_met', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('from_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='enrollment.classarm')),
                ('from_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_from', to='academics.academicsession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_records', to='enrollment.studentprofile')),
                ('to_class', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='enrollment.classarm')),
                ('to_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions_to', to='academics.academicsession')),
            ],
            options={
                'ordering': ['-decided_at'],
            },
        ),
        migrations.CreateModel(
            name='PromotionCriteria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_subjects_to_pass', models.PositiveSmallIntegerField(default=5)),
                ('min_average_score', models.DecimalField(decimal_places=2, default=40, max_digits=5)),
                ('min_attendance_pct', models.PositiveSmallIntegerField(default=50)),
                ('auto_promote_if_met', models.BooleanField(default=False)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_criteria', to='enrollment.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotion_criteria', to='tenants.school')),
            ],
            options={
                'unique_together': {('school', 'class_level')},
            },
        ),
    ]
