import React, { useEffect, useState, useRef } from 'react';
import { useAuth } from '../../hooks/useAuth';
import api from '../../services/api';
import './PortalDesigns.css';
export const DESIGNS = [
  {id:'scholar',name:'Scholar',tag:'Calm and confident',description:'A deep-colour sidebar, spacious cards and a clear daily overview.',colors:['#173B56','#256D85','#D8A548'],font:"'Segoe UI', sans-serif"},
  {id:'campus',name:'Campus',tag:'Open and welcoming',description:'A broad school masthead with horizontal navigation and an open canvas.',colors:['#145B4B','#248C72','#E3B860'],font:"'Segoe UI', sans-serif"},
  {id:'studio',name:'Studio',tag:'Modern and focused',description:'A slim white navigation rail and a compact, editorial workspace.',colors:['#48418C','#7762B0','#E6AF92'],font:'Arial, sans-serif'},
  {id:'executive',name:'Executive',tag:'Distinctive and composed',description:'A right-hand navigation panel, rounded feature area and two-column actions.',colors:['#243E42','#397A7C','#DFAD67'],font:"'Segoe UI', sans-serif"},
  {id:'heritage',name:'Heritage',tag:'Timeless and considered',description:'A centred school crest, classic typography and a framed, tabbed workspace.',colors:['#6B3040','#8C5D63','#C3A05A'],font:'Georgia, serif'},
];
const initial = {...DESIGNS[0],layout:'scholar',primary_color:'#173B56',secondary_color:'#256D85',accent_color:'#D8A548',font_family:"'Segoe UI', sans-serif"};
function errorText(e) {const data=e.response?.data;return data?.detail || data?.error || (data ? JSON.stringify(data) : 'Unable to save. Please try again.');}
export function DesignPreview({layout,theme,name='Your school',logo='',large=false}) {
  return <div className={'design-preview preview-'+layout+(large?' preview-large':'')} style={{'--preview-primary':theme.primary_color,'--preview-secondary':theme.secondary_color,'--preview-accent':theme.accent_color,fontFamily:theme.font_family}} aria-label={layout+' layout preview'}>
    <div className="preview-nav"><div className="preview-brand">{logo?<img src={logo} alt=""/>:<b>{name.slice(0,1)}</b>}<strong>{name}</strong></div><div className="preview-links">{['Dashboard','Students','Calendar','School fees','Results'].map((v,i)=><span key={v} className={i===0?'selected':''}>{v}</span>)}</div></div>
    <div className="preview-body"><div className="preview-toolbar"><span>School workspace</span><i/></div><div className="preview-content"><div className="preview-hero"><small>WELCOME TO YOUR SCHOOL</small><strong>Your school, connected.</strong><span>A place for every learner.</span><i/></div><div className="preview-cards">{['Student directory','Academic calendar','Fee collection','Question bank'].map(v=><div key={v}><i/><strong>{v}</strong><span/></div>)}</div><div className="preview-bottom"><div><span/><span/><span/></div><div><i/><i/><i/><i/><i/></div></div></div></div>
  </div>;
}
export default function PortalDesigns() {
  const {user}=useAuth();const allowed=user?.platformAccess!=='viewer';
  const [catalog,setCatalog]=useState(null),[school,setSchool]=useState(null),[schoolId,setSchoolId]=useState(''),[theme,setTheme]=useState(initial),[plan,setPlan]=useState('free'),[logo,setLogo]=useState(''),[logoName,setLogoName]=useState(''),[motto,setMotto]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(false);
  const generation=useRef(0);
  useEffect(()=>{if(allowed)api.get('/api/platform/appearance/').then(r=>{setCatalog(r.data);const requested=new URLSearchParams(window.location.search).get('school');if(requested)setSchoolId(requested);}).catch(e=>setError(errorText(e)));},[allowed]);
  useEffect(()=>{const version=++generation.current;if(!schoolId){setSchool(null);return;}setLoading(true);setSchool(null);setNotice('');setError('');api.get('/api/platform/schools/'+schoolId+'/').then(r=>{if(version!==generation.current)return;setSchool(r.data);setTheme({...initial,...r.data.theme});setPlan(r.data.subscription_plan);setLogo(r.data.logo || '');setMotto(r.data.motto || '');}).catch(e=>{if(version===generation.current)setError(errorText(e));}).finally(()=>{if(version===generation.current)setLoading(false);});},[schoolId]);
  const selectDesign=d=>{setTheme({layout:d.id,primary_color:d.colors[0],secondary_color:d.colors[1],accent_color:d.colors[2],font_family:d.font});setNotice('');};
  async function chooseLogo(event){const file=event.target.files?.[0];if(!file)return;setError('');if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2*1024*1024){setError('Choose a PNG, JPEG or WebP image up to 2 MB.');event.target.value='';return;}setBusy(true);try{const form=new FormData();form.append('logo',file);const response=await api.post('/api/platform/schools/'+school.id+'/logo/',form,{headers:{'Content-Type':'multipart/form-data'}});setLogo(response.data.logo);setLogoName(file.name);setNotice('School logo uploaded.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function removeLogo(){setBusy(true);setError('');try{await api.delete('/api/platform/schools/'+school.id+'/logo/');setLogo('');setLogoName('');setNotice('School logo removed.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  async function save(){setBusy(true);setError('');setNotice('');try{const {layout,primary_color,secondary_color,accent_color,font_family}=theme;await api.patch('/api/platform/schools/'+school.id+'/',{theme_config:{layout,primary_color,secondary_color,accent_color,font_family},subscription_plan:plan,motto});setNotice('Saved. The school will see its new design and plan features on the next page reload.');}catch(e){setError(errorText(e));}finally{setBusy(false);}}
  if(!allowed)return <main className="design-studio"><h1>Owner access required</h1><p>Only platform owners can assign school designs and plans.</p></main>;
  return <main className="design-studio"><div className="design-page-heading"><div><span className="workspace-eyebrow">MAKE EVERY SCHOOL ITS OWN</span><h1>A portal with personality.</h1><p>Five considered designs. Your schools' colours. One place to make it all feel personal.</p></div><span className="design-count">05 <small>PORTAL DESIGNS</small></span></div>
    {error&&<p className="design-error" role="alert">{error}</p>}{notice&&<p className="design-notice" role="status">{notice}</p>}
    <div className="design-school-picker"><label htmlFor="design-school">Choose a school</label><select id="design-school" disabled={busy} value={schoolId} onChange={e=>setSchoolId(e.target.value)}><option value="">Select a school to customise</option>{catalog?.schools.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select><p>Preview first. Changes are applied only when you save.</p></div>
    {loading&&<p role="status">Loading school design...</p>}
    <fieldset disabled={!school || busy || loading} className="design-fieldset"><legend>01 / Choose the layout</legend><div className="design-gallery">{DESIGNS.map(d=><button type="button" key={d.id} aria-pressed={theme.layout===d.id} onClick={()=>selectDesign(d)} className={'design-option'+(theme.layout===d.id?' chosen':'')}><DesignPreview layout={d.id} theme={{primary_color:d.colors[0],secondary_color:d.colors[1],accent_color:d.colors[2]}} name={school?.name || 'Your school'}/><div className="design-option-caption"><div><strong>{d.name}</strong><span>{d.tag}</span></div><i aria-hidden="true">{theme.layout===d.id?'✓':'↗'}</i></div><p>{d.description}</p></button>)}</div></fieldset>
    {school&&<><div className="design-edit-grid"><section className="design-controls"><fieldset disabled={busy} className="design-fieldset"><legend>02 / Make it theirs</legend><h2>School identity</h2><label>Choose school logo<input aria-label="Choose school logo" type="file" accept="image/png,image/jpeg,image/webp" onChange={chooseLogo}/></label>{logoName&&<span>{logoName}</span>}{logo&&<button type="button" onClick={removeLogo}>Remove logo</button>}<p className="design-help">PNG, JPEG or WebP, up to 2 MB.</p><label>School motto<input maxLength={255} value={motto} onChange={e=>setMotto(e.target.value)}/></label><div className="design-colors">{[['primary_color','Primary'],['secondary_color','Secondary'],['accent_color','Accent']].map(([key,label])=><label key={key}>{label}<input type="color" aria-label={label} value={theme[key]} onChange={e=>setTheme({...theme,[key]:e.target.value})}/><span>{theme[key]}</span></label>)}</div><label>Typography<select value={theme.font_family} onChange={e=>setTheme({...theme,font_family:e.target.value})}><option value="'Segoe UI', sans-serif">Modern / Segoe UI</option><option value="Arial, sans-serif">Clean / Arial</option><option value="Georgia, serif">Classic / Georgia</option><option value="Roboto, sans-serif">Neutral / Roboto</option></select></label><p className="design-help">Text on primary and accent backgrounds adjusts for contrast. Choosing another layout loads its suggested palette.</p></fieldset></section>
    <section className="design-live"><span className="workspace-eyebrow">LIVE DESIGN PREVIEW</span><h2>{school.name}</h2><p>{motto || 'Your school motto'}</p><DesignPreview layout={theme.layout} theme={theme} name={school.name} logo={logo} large/><p className="design-help">Sample content illustrates the layout. Your school's actual pages and records stay in place.</p></section></div>
    <fieldset disabled={busy} className="design-fieldset design-plan-section"><legend>03 / Activate features</legend><h2>The right tools for this school.</h2><div className="design-plan-options">{Object.entries(catalog?.plans || {}).map(([id,features])=><label key={id} className={plan===id?'selected':''}><input type="radio" name="plan" value={id} checked={plan===id} onChange={()=>setPlan(id)}/><strong>{id==='free'?'Setup':id}</strong><ul>{features.map(f=><li key={f}>{catalog.features[f]}</li>)}</ul></label>)}</div><p className="design-help">Plan access is enforced on the server. Assigning a plan here is a manual owner activation and does not charge the school. All five layouts are available on every plan; SMS and other provider usage remain separate charges.</p></fieldset>
    <div className="design-save-bar"><div><strong>{school.name}</strong><span>{DESIGNS.find(d=>d.id===theme.layout)?.name} layout / {plan} plan</span></div><button disabled={busy || loading} onClick={save}>{busy?'Saving...':'Save design and activate plan'}</button><a target="_blank" rel="noreferrer" href={'/school-preview?school='+encodeURIComponent(school.subdomain)}>Preview school sign-in</a></div></>}
  </main>;
}
