# Generated by Django 4.2.16 on 2026-05-11 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('academics', '0002_alter_term_next_term_begins'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('data', models.JSONField(default=dict)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='tenants.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics_snapshots', to='academics.term')),
            ],
            options={
                'ordering': ['-computed_at'],
                'unique_together': {('school', 'term')},
            },
        ),
    ]
