# Generated by Django 5.2.17 on 2026-09-27 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_term_next_term_begins'),
        ('tenants', '0005_alter_school_subscription_plan'),
        ('timetable', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_id', models.PositiveBigIntegerField()),
                ('date', models.DateField()),
                ('term_name', models.CharField(max_length=80)),
                ('class_arm_id_snapshot', models.PositiveBigIntegerField()),
                ('class_name', models.CharField(max_length=160)),
                ('subject_id_snapshot', models.PositiveBigIntegerField()),
                ('subject_name', models.CharField(max_length=160)),
                ('period_name', models.CharField(max_length=50)),
                ('period_start', models.TimeField()),
                ('period_end', models.TimeField()),
                ('scheduled_teacher_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('scheduled_teacher_name', models.CharField(blank=True, max_length=160)),
                ('actual_teacher_name', models.CharField(blank=True, max_length=160)),
                ('outcome', models.CharField(choices=[('delivered', 'Delivered'), ('missed', 'Missed'), ('cancelled', 'Cancelled'), ('substituted', 'Substituted')], max_length=12)),
                ('note', models.CharField(blank=True, max_length=500)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('actual_teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivered_lesson_records', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_lesson_records', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_records', to='tenants.school')),
                ('term', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.term')),
                ('timetable_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_records', to='timetable.timetableentry')),
            ],
            options={
                'indexes': [models.Index(fields=['school', 'date', 'outcome'], name='timetable_l_school__6a00b5_idx')],
                'constraints': [models.UniqueConstraint(fields=('school', 'slot_id', 'date'), name='unique_lesson_slot_date')],
            },
        ),
    ]
