# Generated by Django 4.2.16 on 2026-09-15 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0002_cbtexam_studentexamsession_studentanswer'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexamsession',
            name='deadline_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='question_snapshot',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='student_answers', to='cbt.question'),
        ),
        migrations.AlterField(
            model_name='studentanswer',
            name='selected_option',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
