# Generated by Django 5.2.17 on 2026-09-28 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_term_next_term_begins'),
        ('cbt', '0003_studentexamsession_deadline_at_and_more'),
        ('curriculum', '0001_initial'),
        ('enrollment', '0006_migrationstudentreference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbtexam',
            name='component_key',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
        migrations.AddField(
            model_name='question',
            name='curriculum_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bank_questions', to='curriculum.curriculumtopic'),
        ),
        migrations.AddField(
            model_name='question',
            name='marks',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.CharField(choices=[('bank', 'Question bank'), ('term', 'Term CBT')], default='bank', max_length=8),
        ),
        migrations.AddField(
            model_name='question',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cbt_questions', to='academics.term'),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='class_arm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enrollment.classarm'),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='raw_maximum',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='studentexamsession',
            name='raw_score',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('mcq', 'Multiple Choice'), ('true_false', 'True / False'), ('fill_blank', 'Fill in the Blank'), ('theory', 'Theory / Essay')], default='mcq', max_length=20),
        ),
    ]
