# Generated by Django 5.2.17 on 2026-09-28 08:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_term_next_term_begins'),
        ('cbt', '0004_cbtexam_component_key_question_curriculum_topic_and_more'),
        ('curriculum', '0001_initial'),
        ('enrollment', '0006_migrationstudentreference_and_more'),
        ('tenants', '0005_alter_school_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(default=60)),
                ('blueprint', models.JSONField(default=list)),
                ('question_snapshot', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('approved', 'Approved')], default='draft', max_length=10)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='approved_exam_papers', to=settings.AUTH_USER_MODEL)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.classlevel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_exam_papers', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='OnlineAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField()),
                ('due_at', models.DateTimeField()),
                ('maximum', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('kind', models.CharField(choices=[('practice', 'Practice'), ('graded', 'Graded')], default='practice', max_length=8)),
                ('component_key', models.CharField(blank=True, max_length=32)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed')], default='draft', max_length=9)),
                ('question_snapshot', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('class_arm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.classarm')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('curriculum_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='curriculum.curriculumtopic')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('answers', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted')], default='draft', max_length=9)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('feedback', models.TextField(blank=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='cbt.onlineassignment')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectAssessmentMode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('cbt', 'CBT'), ('paper', 'Paper')], max_length=5)),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
        ),
        migrations.AddConstraint(
            model_name='onlineassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('kind', 'graded')), fields=('school', 'term', 'class_arm', 'subject', 'component_key'), name='unique_graded_assignment_component'),
        ),
        migrations.AddConstraint(
            model_name='assignmentsubmission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='unique_assignment_submission'),
        ),
        migrations.AddConstraint(
            model_name='subjectassessmentmode',
            constraint=models.UniqueConstraint(fields=('school', 'term', 'class_level', 'subject'), name='unique_subject_assessment_mode'),
        ),
    ]
