# Generated by Django 5.2.17 on 2026-09-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbt', '0005_exampaper_onlineassignment_assignmentsubmission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, default='', help_text="Option id for MCQ/true_false (e.g. 'A'), or answer text for fill_blank", max_length=1000),
        ),
    ]
