# Generated by Django 4.2.16 on 2026-09-14 22:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0003_platformsecurity_platformevent'),
        ('enrollment', '0005_add_is_final_year_to_classlevel'),
        ('fees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium')], max_length=20, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months', models.PositiveSmallIntegerField(default=12)),
                ('enabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolPaymentAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('test', 'Test'), ('live', 'Live')], max_length=4)),
                ('subaccount_code', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('account_last_four', models.CharField(blank=True, max_length=4)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_accounts', to='tenants.school')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('fees', 'School fees'), ('subscription', 'Portal subscription')], max_length=20)),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('mode', models.CharField(max_length=4)),
                ('amount_kobo', models.PositiveBigIntegerField()),
                ('currency', models.CharField(default='NGN', max_length=3)),
                ('payer_email', models.EmailField(max_length=254)),
                ('subaccount_code', models.CharField(blank=True, max_length=100)),
                ('allocations', models.JSONField(default=list)),
                ('plan', models.CharField(blank=True, max_length=20)),
                ('months', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('initializing', 'Initializing'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('review', 'Review required')], default='initializing', max_length=20)),
                ('authorization_url', models.URLField(blank=True, max_length=500)),
                ('provider_id', models.CharField(blank=True, max_length=100)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_orders', to='tenants.school')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='enrollment.studentprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='schoolpaymentaccount',
            constraint=models.UniqueConstraint(fields=('school', 'mode'), name='school_payment_mode_unique'),
        ),
        migrations.AddConstraint(
            model_name='schoolpaymentaccount',
            constraint=models.UniqueConstraint(fields=('subaccount_code', 'mode'), name='school_subaccount_mode_unique'),
        ),
    ]
