# Generated by Django 4.2.16 on 2026-09-15 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0003_launch_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='fee_schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='fees.feeschedule'),
        ),
    ]
