# Generated by Django 5.2.17 on 2026-09-15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0001_initial'),
        ('fees', '0004_alter_feepayment_fee_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feepayment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fee_payments', to='enrollment.studentprofile'),
        ),
    ]
