# Generated by Django 4.2.16 on 2026-09-20 13:27

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_alter_school_subscription_plan'),
        ('academics', '0002_alter_term_next_term_begins'),
        ('fees', '0006_refresh_subscription_offers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionoffer',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='TermInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], default='premium', max_length=20)),
                ('active_student_count', models.PositiveIntegerField(default=0)),
                ('snapshot_date', models.DateField()),
                ('standard_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('discount_eligible', models.BooleanField(default=False)),
                ('discount_percentage', models.PositiveSmallIntegerField(default=0)),
                ('discount_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('effective_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('final_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('invoice_number', models.CharField(blank=True, max_length=60, unique=True)),
                ('issue_date', models.DateField(default=django.utils.timezone.localdate)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('pending', 'Pending Payment'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], default='issued', max_length=20)),
                ('paid_date', models.DateTimeField(blank=True, null=True)),
                ('grace_period_days', models.PositiveSmallIntegerField(default=14)),
                ('notes', models.TextField(blank=True)),
                ('audit_snapshot', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_invoices', to='academics.academicsession')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_invoices', to='tenants.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='term_invoices', to='academics.term')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='terminvoice',
            constraint=models.UniqueConstraint(fields=('school', 'academic_session', 'term'), name='unique_term_invoice_per_school_term'),
        ),
    ]
