# Generated by Django 4.2.16 on 2026-09-23 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_demorequest'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fees', '0007_ensure_subscription_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('refund', 'Refund request'), ('duplicate', 'Suspected duplicate'), ('incorrect', 'Incorrect payment'), ('provider', 'Provider discrepancy'), ('manual', 'Manual review')], max_length=20)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('under_review', 'Under Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('provider_pending', 'Provider Pending'), ('provider_failed', 'Provider Failed'), ('resolved', 'Resolved')], default='requested', max_length=20)),
                ('reason', models.TextField(max_length=2000)),
                ('admin_notes', models.TextField(blank=True, max_length=2000)),
                ('provider_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('resolved_at', models.DateTimeField(null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exceptions', to='fees.paymentorder')),
                ('reviewed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentexception',
            constraint=models.UniqueConstraint(fields=('order', 'kind'), name='unique_order_exception_kind'),
        ),
    ]
