# Generated by Django 4.2.16 on 2026-09-23 20:33

from django.db import migrations, models


def seed_enterprise(apps, schema_editor):
    apps.get_model('fees', 'SubscriptionOffer').objects.using(schema_editor.connection.alias).get_or_create(
        plan='enterprise', defaults={'amount': '2500.00', 'months': 3, 'enabled': True},
    )


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0008_payment_exception'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptionoffer',
            name='plan',
            field=models.CharField(choices=[('basic', 'Basic'), ('premium', 'Premium'), ('enterprise', 'Enterprise')], max_length=20, unique=True),
        ),
        migrations.RunPython(seed_enterprise, migrations.RunPython.noop),
    ]
