# Generated by Django 4.2.16 on 2026-09-23 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_school_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('academics', '0002_alter_term_next_term_begins'),
        ('fees', '0009_alter_subscriptionoffer_plan'),
    ]

    operations = [
        migrations.CreateModel(
            name='TermInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(max_length=255)),
                ('session_name', models.CharField(max_length=20)),
                ('term_name', models.CharField(max_length=50)),
                ('plan', models.CharField(max_length=20)),
                ('billing_context', models.CharField(default='subscription', editable=False, max_length=20)),
                ('active_student_count', models.PositiveIntegerField()),
                ('snapshot_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('standard_rate', models.DecimalField(decimal_places=2, max_digits=12)),
                ('discount_applied', models.BooleanField()),
                ('discount_percentage', models.PositiveSmallIntegerField()),
                ('discount_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('effective_rate', models.DecimalField(decimal_places=4, max_digits=14)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=16)),
                ('final_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('currency', models.CharField(default='NGN', editable=False, max_length=3)),
                ('invoice_number', models.CharField(editable=False, max_length=40, unique=True)),
                ('issue_date', models.DateField()),
                ('due_date', models.DateField()),
                ('grace_period_days', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('issued', 'Issued'), ('paid', 'Paid'), ('void', 'Void')], default='issued', max_length=10)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, max_length=500)),
                ('academic_session', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.academicsession')),
                ('issued_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fees.paymentorder')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
            options={
                'ordering': ['-issue_date', '-id'],
                'indexes': [models.Index(fields=['school', 'status', 'due_date'], name='fees_termin_school__0d7670_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='terminvoice',
            constraint=models.UniqueConstraint(fields=('school', 'term', 'billing_context'), name='unique_school_term_invoice'),
        ),
        migrations.AddConstraint(
            model_name='terminvoice',
            constraint=models.CheckConstraint(check=models.Q(('due_date__gte', models.F('issue_date'))), name='invoice_due_after_issue'),
        ),
        migrations.AddConstraint(
            model_name='terminvoice',
            constraint=models.CheckConstraint(check=models.Q(('final_amount__gte', 0)), name='invoice_nonnegative_total'),
        ),
        migrations.AddConstraint(
            model_name='terminvoice',
            constraint=models.CheckConstraint(check=models.Q(models.Q(('paid_at__isnull', True), ('payment__isnull', True), ('status', 'issued'), ('voided_at__isnull', True)), models.Q(('paid_at__isnull', False), ('payment__isnull', False), ('status', 'paid'), ('voided_at__isnull', True)), models.Q(('paid_at__isnull', True), ('payment__isnull', True), ('status', 'void'), ('voided_at__isnull', False)), _connector='OR'), name='invoice_valid_lifecycle'),
        ),
    ]
