# Generated by Django 4.2.16 on 2026-09-24 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fees', '0010_terminvoice_terminvoice_unique_school_term_invoice_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentorder',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment_attempts', to='fees.terminvoice'),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='received_amount_kobo',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='received_currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='paymentorder',
            name='verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='terminvoice',
            name='subscription_months',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.UniqueConstraint(condition=models.Q(('invoice__isnull', False), ('status__in', ['initializing', 'pending'])), fields=('invoice',), name='one_open_invoice_checkout'),
        ),
        migrations.AddConstraint(
            model_name='paymentorder',
            constraint=models.CheckConstraint(check=models.Q(('invoice__isnull', True), ('kind', 'subscription'), _connector='OR'), name='invoice_subscription_only'),
        ),
    ]
