# Generated by Django 5.2.17 on 2026-09-27 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def mark_legacy_accounts(apps, schema_editor):
    Payment = apps.get_model('fees', 'FeePayment')
    Account = apps.get_model('fees', 'StudentFinanceAccount')
    pairs = Payment.objects.using(schema_editor.connection.alias).order_by().values_list(
        'school_id', 'student_id').distinct().iterator(chunk_size=1000)
    batch = []
    for school_id, student_id in pairs:
        batch.append(Account(school_id=school_id, student_id=student_id, state='legacy_review'))
        if len(batch) == 500:
            Account.objects.using(schema_editor.connection.alias).bulk_create(batch, ignore_conflicts=True)
            batch.clear()
    if batch:
        Account.objects.using(schema_editor.connection.alias).bulk_create(batch, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_term_next_term_begins'),
        ('enrollment', '0006_migrationstudentreference_and_more'),
        ('fees', '0011_paymentorder_invoice_and_more'),
        ('tenants', '0005_alter_school_subscription_plan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentFinanceAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('active', 'Active'), ('legacy_review', 'Legacy balance needs review')], max_length=20)),
                ('cutover_at', models.DateTimeField(auto_now_add=True)),
                ('opened_at', models.DateTimeField(blank=True, null=True)),
                ('opened_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='finance_account', to='enrollment.studentprofile')),
            ],
        ),
        migrations.CreateModel(
            name='StudentLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('charge', 'Charge'), ('opening', 'Opening balance'), ('payment', 'Payment'), ('discount', 'Discount'), ('scholarship', 'Scholarship'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal')], max_length=20)),
                ('signed_amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('description', models.CharField(max_length=200)),
                ('class_name_snapshot', models.CharField(blank=True, max_length=100)),
                ('due_date_snapshot', models.DateField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('reference', models.CharField(blank=True, max_length=100)),
                ('effective_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor_name', models.CharField(blank=True, max_length=300)),
                ('idempotency_key', models.CharField(blank=True, max_length=100)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('fee_payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entry', to='fees.feepayment')),
                ('fee_schedule', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='fees.feeschedule')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ledger_entries', to='enrollment.studentprofile')),
                ('term', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='StudentPaymentAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('charge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='charge_allocations', to='fees.studentledgerentry')),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_allocations', to='fees.studentledgerentry')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
            ],
        ),
        migrations.AddIndex(
            model_name='studentledgerentry',
            index=models.Index(fields=['school', 'student', 'id'], name='fees_studen_school__37aa66_idx'),
        ),
        migrations.AddIndex(
            model_name='studentledgerentry',
            index=models.Index(fields=['school', 'term', 'student'], name='fees_studen_school__11ce65_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('fee_schedule__isnull', False), ('kind', 'charge')), fields=('school', 'student', 'fee_schedule'), name='unique_student_schedule_charge'),
        ),
        migrations.AddConstraint(
            model_name='studentledgerentry',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('school', 'idempotency_key'), name='unique_student_ledger_retry_key'),
        ),
        migrations.AddConstraint(
            model_name='studentledgerentry',
            constraint=models.CheckConstraint(condition=~models.Q(signed_amount=0) | models.Q(kind='opening'), name='student_ledger_nonzero'),
        ),
        migrations.AddConstraint(
            model_name='studentpaymentallocation',
            constraint=models.UniqueConstraint(fields=('credit', 'charge'), name='unique_credit_charge_allocation'),
        ),
        migrations.AddConstraint(
            model_name='studentpaymentallocation',
            constraint=models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='student_allocation_positive'),
        ),
        migrations.RunPython(mark_legacy_accounts, migrations.RunPython.noop),
    ]
