# Generated by Django 5.2.17 on 2026-09-27 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_term_next_term_begins'),
        ('enrollment', '0006_migrationstudentreference_and_more'),
        ('tenants', '0005_alter_school_subscription_plan'),
        ('timetable', '0002_lessonrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurriculumPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_level', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.classlevel')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='enrollment.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='academics.term')),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField()),
                ('label', models.CharField(blank=True, max_length=80)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='weeks', to='curriculum.curriculumplan')),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='CurriculumTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=180)),
                ('description', models.CharField(blank=True, max_length=500)),
                ('position', models.PositiveSmallIntegerField(default=1)),
                ('archived', models.BooleanField(default=False)),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topics', to='curriculum.curriculumweek')),
            ],
            options={
                'ordering': ['week__number', 'position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LearningObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('position', models.PositiveSmallIntegerField()),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='objectives', to='curriculum.curriculumtopic')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
        migrations.CreateModel(
            name='TopicCoverage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(choices=[('partial', 'Partial'), ('covered', 'Covered')], max_length=8)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topic_coverage', to='timetable.lessonrecord')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenants.school')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='coverage', to='curriculum.curriculumtopic')),
            ],
        ),
        migrations.AddConstraint(
            model_name='curriculumplan',
            constraint=models.UniqueConstraint(fields=('school', 'term', 'class_level', 'subject'), name='unique_curriculum_scope'),
        ),
        migrations.AddConstraint(
            model_name='curriculumweek',
            constraint=models.UniqueConstraint(fields=('plan', 'number'), name='unique_curriculum_week'),
        ),
        migrations.AddConstraint(
            model_name='curriculumtopic',
            constraint=models.UniqueConstraint(fields=('week', 'position'), name='unique_topic_position'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(fields=('topic', 'position'), name='unique_objective_position'),
        ),
        migrations.AddConstraint(
            model_name='learningobjective',
            constraint=models.UniqueConstraint(fields=('topic', 'text'), name='unique_objective_text'),
        ),
        migrations.AddIndex(
            model_name='topiccoverage',
            index=models.Index(fields=['school', 'topic', 'active'], name='curriculum__school__8b9e45_idx'),
        ),
        migrations.AddConstraint(
            model_name='topiccoverage',
            constraint=models.UniqueConstraint(fields=('lesson', 'topic'), name='unique_lesson_topic_coverage'),
        ),
    ]
