# Generated by Django 5.1.7 on 2026-03-19 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0003_subjectassignment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='classarm',
            options={'ordering': ['class_level__order_index', 'name'], 'verbose_name': 'Class Arm', 'verbose_name_plural': 'Class Arms'},
        ),
        migrations.AlterModelOptions(
            name='classlevel',
            options={'ordering': ['order_index', 'name'], 'verbose_name': 'Class Level', 'verbose_name_plural': 'Class Levels'},
        ),
        migrations.AlterModelOptions(
            name='studentprofile',
            options={'ordering': ['school', 'admission_number'], 'verbose_name': 'Student Profile', 'verbose_name_plural': 'Student Profiles'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'ordering': ['name'], 'verbose_name': 'Subject', 'verbose_name_plural': 'Subjects'},
        ),
        migrations.RenameIndex(
            model_name='staffprofile',
            new_name='enrollment__school__8a7014_idx',
            old_name='enrollment_sp_staff_status_idx',
        ),
        migrations.RenameIndex(
            model_name='staffprofile',
            new_name='enrollment__staff_i_3361ad_idx',
            old_name='enrollment_sp_staff_id_idx',
        ),
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='enrollment__school__4d1583_idx',
            old_name='enrollment_sp_school_status_idx',
        ),
        migrations.RenameIndex(
            model_name='studentprofile',
            new_name='enrollment__admissi_161c9b_idx',
            old_name='enrollment_sp_adm_num_idx',
        ),
        migrations.RenameIndex(
            model_name='subjectassignment',
            new_name='enrollment__school__e3aa42_idx',
            old_name='enrollment_sa_school_term_idx',
        ),
        migrations.RenameIndex(
            model_name='subjectassignment',
            new_name='enrollment__teacher_71656d_idx',
            old_name='enrollment_sa_teacher_term_idx',
        ),
        migrations.RenameIndex(
            model_name='subjectassignment',
            new_name='enrollment__class_a_38b9d2_idx',
            old_name='enrollment_sa_arm_term_idx',
        ),
        migrations.AlterField(
            model_name='classarm',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='homeroom_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='classarm',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classarm',
            name='name',
            field=models.CharField(help_text="Arm letter(s), e.g. 'A', 'B', 'Gold'", max_length=10),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='classlevel',
            name='order_index',
            field=models.PositiveSmallIntegerField(default=0, help_text='Ascending order for display (0 = JSS1 first).'),
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Auto-generated: SLUG-YYYY-XXXX', max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='Date of Birth'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='guardian_relationship',
            field=models.CharField(blank=True, choices=[('father', 'Father'), ('mother', 'Mother'), ('guardian', 'Guardian'), ('sibling', 'Sibling'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='subject',
            name='class_levels',
            field=models.ManyToManyField(blank=True, help_text='Which class levels this subject is offered to.', related_name='subjects', to='enrollment.classlevel'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(help_text='Short code, e.g. ENG, MTH, PHY', max_length=10),
        ),
        migrations.AlterField(
            model_name='subject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='max_ca_score',
            field=models.PositiveSmallIntegerField(default=40, help_text='Maximum continuous assessment score (default 40).'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='max_exam_score',
            field=models.PositiveSmallIntegerField(default=60, help_text='Maximum examination score (default 60).'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='subjectassignment',
            name='teacher',
            field=models.ForeignKey(limit_choices_to={'user__role': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='subject_assignments', to='enrollment.staffprofile'),
        ),
    ]
