# Generated by Django 4.2.16 on 2026-05-11 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0004_alter_classarm_options_alter_classlevel_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classlevel',
            name='is_final_year',
            field=models.BooleanField(default=False, help_text='Students at this level are graduated rather than promoted.'),
        ),
    ]
