# Generated by Django 4.2.16 on 2026-09-26 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0005_alter_school_subscription_plan'),
        ('enrollment', '0005_add_is_final_year_to_classlevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MigrationStudentReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=80)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.school')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='migration_reference', to='enrollment.studentprofile')),
            ],
        ),
        migrations.AddConstraint(
            model_name='migrationstudentreference',
            constraint=models.UniqueConstraint(fields=('school', 'reference'), name='unique_migration_student_ref'),
        ),
    ]
