# Generated by Django 5.2.17 on 2026-10-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0016_batch22_admission_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentprofile',
            name='admission_number',
            field=models.CharField(blank=True, help_text='Auto-generated: SLUG-YYYY-XXXX', max_length=128, unique=True),
        ),
    ]
