# Generated by Django 5.2.17 on 2026-10-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enrollment', '0017_widen_student_admission_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstitutionalIdentifierSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namespace', models.CharField(max_length=128, unique=True)),
                ('last_value', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='staffprofile',
            name='staff_id',
            field=models.CharField(blank=True, help_text='Auto-generated: SLUG-STAFF-XXXX', max_length=128, unique=True),
        ),
    ]
