import React, {useEffect, useState} from 'react';
import {Link, useLocation} from 'react-router-dom';
import api from '../../services/api';
import './Marketing.css';

const plans=[['Basic','₦800','School setup, people and academic calendar; attendance; results; fees and receipts; timetables; notifications'],['Premium','₦1,500','Everything in Basic, plus CBT exams, analytics, bulk imports, promotion workflows and scratch cards']];
const features=['School administration and student records','Attendance, results and report cards','Fee management and receipt access','Role-based spaces for administrators, teachers, students and parents','Timetables, communication tools and secure sign-in'];
const title={"/":"Customized digital portals for schools","/features":"Features","/pricing":"Pricing","/demo":"Request a Demo","/contact":"Contact","/privacy":"Privacy","/terms":"Terms"};
function Layout({children}) {const {pathname}=useLocation(); useEffect(()=>{document.title=`${title[pathname]||'Paideia Portals'} | Paideia Portals`;},[pathname]); return <div className="marketing"><a className="skip" href="#main">Skip to content</a><header><Link className="brand" to="/"><img src="/favicon.svg" alt="Paideia Portals"/><span>Paideia <small>PORTALS</small></span></Link><nav aria-label="Main navigation"><Link to="/features">Features</Link><Link to="/pricing">Pricing</Link><Link to="/demo">Request a demo</Link><Link to="/login" className="portal-link">Access your portal</Link></nav></header><main id="main">{children}</main><footer><strong>Paideia Portals</strong><span>Customized digital portals built for schools.</span><div><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link><Link to="/contact">Contact</Link></div></footer></div>}
const CTA=()=> <div className="cta"><Link className="button" to="/demo">Request a demo</Link><Link className="button secondary" to="/features">Explore features</Link></div>;
function Home(){return <Layout><section className="hero"><div><p className="eyebrow">PAIDEIA PORTALS</p><h1>Customized digital portals built for schools.</h1><p className="lead">Bring school records, learning, fees and family access into one configured digital experience for your community.</p><CTA/><p><Link to="/login">Already a customer? Access your portal.</Link></p></div><aside className="preview" aria-label="Product preview placeholder"><span>YOUR SCHOOL</span><strong>One connected school experience</strong><p>Administrator · Teacher · Student · Parent</p></aside></section><section><h2>Less administration. More clarity.</h2><div className="grid">{['Bring fragmented records together','Make results and attendance easier to manage','Give parents and students clearer access','See fee payments and receipts in context'].map(x=><article key={x}><h3>{x}</h3><p>Paideia gives each school a configured portal for the work that matters every day.</p></article>)}</div></section><section><h2>Built around your school community</h2><div className="grid roles"><article><h3>Administrators</h3><p>Manage school setup, people, fees and academic operations.</p></article><article><h3>Teachers</h3><p>Record attendance, enter scores and support learners.</p></article><article><h3>Students and parents</h3><p>Access relevant school information through role-based accounts.</p></article></div></section><section><h2>How it works</h2><ol className="steps"><li>Request a demo</li><li>Discuss your school’s requirements</li><li>We configure your portal</li><li>Onboard your users</li><li>Start using Paideia</li></ol></section><section className="price-call"><h2>Simple, per-student pricing</h2><p>From ₦800 per active student per term. Schools with 100 or more active students receive an automatic 10% discount.</p><Link className="button" to="/pricing">View pricing</Link></section></Layout>}
function Features(){return <Layout><section className="page-intro"><p className="eyebrow">FEATURES</p><h1>One configured portal, built around school work.</h1><p className="lead">Paideia combines practical academic and administrative workflows in a branded school experience.</p></section><section className="grid">{features.map(x=><article key={x}><h2>{x}</h2><p>Available according to your school’s subscription plan and configured workflow.</p></article>)}</section><section><h2>Designed for every role</h2><p>Administrators coordinate the school. Teachers manage learning activities. Students and parents use focused, secure views of the information relevant to them.</p></section><CTA/></Layout>}
function Pricing(){return <Layout><section className="page-intro"><p className="eyebrow">PRICING</p><h1>Clear pricing that grows with your school.</h1><p className="lead">Subscription pricing is based on active students and billed per term.</p></section><section className="plans">{plans.map(([name,price,detail])=><article key={name}><h2>{name}</h2><p className="price">{price}<small> per active student / term</small></p><p>{detail}</p><Link className="button" to="/demo">Request a demo</Link></article>)}</section><section className="notice"><h2>100+ active students</h2><p>An automatic 10% discount applies when your school has 100 or more active students.</p></section></Layout>}
function Demo(){const [form,setForm]=useState({school_name:'',contact_name:'',email:'',phone:'',student_population:'',location:'',message:'',website:''}),[state,setState]=useState(''); const submit=async e=>{e.preventDefault();if(form.website)return;setState('');try{await api.post('/api/demo-requests/',form);setState('Thanks. Your demo request has been received.');e.target.reset();}catch(e){setState(e.response?.data?.detail||'Please check the form and try again.');}};return <Layout><section className="page-intro"><p className="eyebrow">REQUEST A DEMO</p><h1>Tell us about your school.</h1><p>We will use these details to understand your requirements. Fields marked required are needed to respond.</p></section><form className="demo-form" onSubmit={submit}>{[['school_name','School name'],['contact_name','Contact name'],['email','Work email'],['phone','Phone number'],['student_population','Approximate active students'],['location','Location']].map(([name,label])=><label key={name}>{label}<input required type={name==='email'?'email':name==='student_population'?'number':'text'} min={name==='student_population'?1:undefined} name={name} onChange={e=>setForm({...form,[name]:e.target.value})}/></label>)}<label className="honeypot">Website<input name="website" tabIndex="-1" autoComplete="off" onChange={e=>setForm({...form,website:e.target.value})}/></label><label className="full">Message or requirements<textarea name="message" maxLength="2000" onChange={e=>setForm({...form,message:e.target.value})}/></label><button className="button">Send request</button>{state&&<p role="status">{state}</p>}</form></Layout>}
function TextPage({kind}){const privacy=kind==='privacy';return <Layout><section className="legal"><p className="eyebrow">DRAFT FOR REVIEW</p><h1>{privacy?'Privacy policy':'Terms of service'}</h1><p>This draft needs business and legal review before publication as a final policy.</p><h2>{privacy?'Information and school data':'Using Paideia'}</h2><p>{privacy?'Paideia processes account, school and student information that schools provide to operate their portal. Schools are responsible for the information they enter and the people they authorize.':'Schools are responsible for their accounts, authorized users, acceptable use and payment of subscriptions. Access may be limited or ended according to the agreed service arrangement.'}</p><h2>{privacy?'Access and retention':'Availability, payments and data'}</h2><p>{privacy?'Access is controlled through role-based accounts. Retention, support contacts, legal basis and data-request procedures require confirmation with the business and legal advisers.':'Service availability, billing, termination, data handling, limitations and support arrangements require confirmation in the school service agreement.'}</p></section></Layout>}
function Contact(){return <Layout><section className="page-intro"><p className="eyebrow">CONTACT</p><h1>Let’s discuss your school portal.</h1><p>Use the demo request form to share your school’s requirements. Official business contact details will be published here after business confirmation.</p><CTA/></section></Layout>}
export const MarketingPage=({page})=>({home:<Home/>,features:<Features/>,pricing:<Pricing/>,demo:<Demo/>,contact:<Contact/>,privacy:<TextPage kind="privacy"/>,terms:<TextPage kind="terms"/>}[page]);
