import React, { useEffect, useState } from 'react';
import { Link, useLocation } from 'react-router-dom';
import api from '../../services/api';
import './Marketing.css';

const lightLogo = '/media/brand/paideia-full-light.jpeg';
const darkLogo = '/media/brand/paideia-full-dark.jpeg';
const pages = {
  '/': ['A digital home for every school', 'Paideia gives schools a configured portal for administration, teaching, learning and family access.'],
  '/features': ['Explore the platform', 'See how school work connects across Paideia Portals.'],
  '/pricing': ['Pricing', 'Clear per-student pricing for your school portal.'],
  '/demo': ['Request a demo', 'Discuss a Paideia portal configured around your school.'],
  '/contact': ['Contact', 'Start a conversation about your school portal.'],
  '/privacy': ['Privacy draft', 'How Paideia handles school and student information.'],
  '/terms': ['Terms draft', 'Draft terms for using Paideia Portals.'],
};
const roles = [
  { name: 'Administrator', line: 'Keep the school moving.', description: 'Coordinate students, staff, subjects, calendars, fees and school operations.', areas: ['Student records', 'School calendar', 'Fee setup'] },
  { name: 'Teacher', line: 'Make teaching work easier to follow.', description: 'Record attendance, enter scores and see the timetable for assigned classes.', areas: ['Attendance', 'Score entry', 'Timetable'] },
  { name: 'Student', line: 'See what matters today.', description: 'Reach timetable, results, attendance and fee information through a focused account.', areas: ['Timetable', 'Results', 'Fee status'] },
  { name: 'Parent', line: 'Stay connected to your child.', description: 'Linked parents can follow results, attendance and fee information.', areas: ['Linked child', 'Results', 'Attendance'] },
];
const outcomes = [
  ['01', 'Run the school', 'Keep people, subjects, classes and the academic calendar in a coherent working space.'],
  ['02', 'Manage academics', 'Follow attendance and scores through to report cards and performance views.'],
  ['03', 'Understand fees', 'Set fees, track balances, verify online payments and retrieve receipts.'],
  ['04', 'Connect families', 'Give students and linked parents information relevant to their school lives.'],
];

function Layout({ children }) {
  const { pathname } = useLocation();
  const [menuOpen, setMenuOpen] = useState(false);
  useEffect(() => {
    const [title, description] = pages[pathname] || pages['/'];
    document.title = `${title} | Paideia Portals`;
    document.querySelector('meta[name="description"]')?.setAttribute('content', description);
    document.querySelector('meta[property="og:title"]')?.setAttribute('content', `${title} | Paideia Portals`);
    document.querySelector('meta[property="og:description"]')?.setAttribute('content', description);
    document.querySelector('meta[property="og:image"]')?.setAttribute('content', `${window.location.origin}${lightLogo}`);
    document.querySelector('link[rel="canonical"]')?.setAttribute('href', `${window.location.origin}${pathname}`);
    setMenuOpen(false);
  }, [pathname]);
  useEffect(() => {
    if (!menuOpen) return undefined;
    const close = event => { if (event.key === 'Escape') setMenuOpen(false); };
    document.addEventListener('keydown', close);
    return () => document.removeEventListener('keydown', close);
  }, [menuOpen]);
  return <div className="marketing">
    <a className="marketing-skip" href="#marketing-main">Skip to content</a>
    <header className="marketing-header"><div className="marketing-shell marketing-header-inner">
      <Link className="marketing-brand" to="/" aria-label="Paideia Portals home"><img src={lightLogo} alt=""/><span>Paideia <small>PORTALS</small></span></Link>
      <button className="marketing-menu-button" type="button" aria-expanded={menuOpen} aria-controls="marketing-navigation" onClick={() => setMenuOpen(!menuOpen)}>{menuOpen ? 'Close' : 'Menu'} <span aria-hidden="true">{menuOpen ? '×' : '☰'}</span></button>
      <nav id="marketing-navigation" className={menuOpen ? 'marketing-nav is-open' : 'marketing-nav'} aria-label="Main navigation">
        <Link to="/features">Features</Link><Link to="/pricing">Pricing</Link><Link to="/demo">Demo</Link><Link to="/contact">Contact</Link>
        <Link className="marketing-portal-link" to="/login">Access your portal</Link><Link className="marketing-nav-cta" to="/demo">Request a demo <span aria-hidden="true">↗</span></Link>
      </nav>
    </div></header>
    <main id="marketing-main">{children}</main>
    <footer className="marketing-footer"><div className="marketing-shell marketing-footer-inner"><img src={darkLogo} loading="lazy" alt="Paideia Portals — Cultivating minds. Building futures."/><p>Digital school environments configured for the communities they serve.</p><nav aria-label="Footer navigation"><Link to="/features">Features</Link><Link to="/pricing">Pricing</Link><Link to="/contact">Contact</Link><Link to="/privacy">Privacy</Link><Link to="/terms">Terms</Link></nav></div></footer>
  </div>;
}

function Actions() { return <div className="marketing-actions"><Link className="marketing-button" to="/demo">Request a demo <span aria-hidden="true">↗</span></Link><Link className="marketing-text-link" to="/features">Explore the platform <span aria-hidden="true">→</span></Link></div>; }

// An annotated workflow, with no invented school account or metrics. Replace its
// illustrated frames with approved captures from a synthetic school:
// /media/product/admin-dashboard.webp, teacher-dashboard.webp,
// student-dashboard.webp, parent-dashboard.webp (1600 x 1000 each), plus
// /media/product/results.webp and fee-receipt.webp (1600 x 1000 each).
function ProductComposition() { return <div className="product-composition" aria-label="Illustrated map of Paideia's portal areas"><div className="product-frame"><div className="product-frame-bar"><span aria-hidden="true">● ● ●</span><span>PAIDEIA / SCHOOL WORKSPACE</span></div><div className="product-frame-body"><div className="product-frame-rail"><span>Overview</span><span>People</span><span>Academics</span><span>Fees</span></div><div className="product-frame-main"><p>School operations</p><strong>One connected workspace</strong><div className="product-module-grid"><div><small>PEOPLE</small><b>Students & staff</b><span>Records and school roles</span></div><div><small>ACADEMICS</small><b>Attendance & results</b><span>Classroom to report card</span></div><div><small>FINANCE</small><b>Fees & receipts</b><span>Payment visibility</span></div></div><div className="product-flow"><span>School setup</span><b>→</b><span>Daily work</span><b>→</b><span>Family access</span></div></div></div></div><div className="product-side-note"><span className="marketing-overline">FOUR CONNECTED SPACES</span><strong>Admin / Teacher / Student / Parent</strong><small>Illustrated workflow · product screenshots to follow</small></div></div>; }

function RoleShowcase() {
  const [selected, setSelected] = useState(0);
  const role = roles[selected];
  return <section className="marketing-section marketing-role-section"><div className="marketing-shell"><div className="marketing-section-intro"><p className="marketing-overline">THE PAIDEIA ECOSYSTEM</p><h2>One school. Four focused experiences.</h2><p>Everyone sees the part of school life they need, without making every role work inside the same dashboard.</p></div><div className="role-showcase"><div className="role-tabs" role="tablist" aria-label="Portal roles">{roles.map((item, index) => <button key={item.name} type="button" role="tab" id={`role-tab-${index}`} aria-controls="role-panel" aria-selected={selected === index} tabIndex={selected === index ? 0 : -1} onClick={() => setSelected(index)} onKeyDown={event => { if (event.key === 'ArrowRight' || event.key === 'ArrowLeft') { event.preventDefault(); const next = (selected + (event.key === 'ArrowRight' ? 1 : -1) + roles.length) % roles.length; setSelected(next); document.getElementById(`role-tab-${next}`)?.focus(); } }}>{item.name}</button>)}</div><div id="role-panel" className="role-panel" role="tabpanel" aria-labelledby={`role-tab-${selected}`}><div><p className="marketing-overline">{role.name.toUpperCase()} PORTAL</p><h3>{role.line}</h3><p>{role.description}</p><ul>{role.areas.map(area => <li key={area}>{area}</li>)}</ul></div><div className="role-visual" aria-label={`${role.name} product areas`}><div className="role-visual-top"><span>{role.name.toUpperCase()} / WORKSPACE AREAS</span><span aria-hidden="true">↗</span></div>{role.areas.map((area, index) => <div className="role-visual-row" key={area}><span>0{index + 1}</span><strong>{area}</strong><span aria-hidden="true">→</span></div>)}<small>Illustrated interface areas; no live school data.</small></div></div></div></div></section>;
}

function Home() { return <Layout>
  <section className="marketing-hero"><div className="marketing-shell marketing-hero-grid"><div className="marketing-hero-copy"><p className="marketing-overline">A BETTER DIGITAL HOME FOR SCHOOL</p><h1>Your school deserves a portal that feels like yours.</h1><p>Paideia connects administration, teachers, students and parents in one digital environment configured for your school.</p><Actions/><Link className="marketing-existing" to="/login">Already using Paideia? Access your portal <span aria-hidden="true">→</span></Link></div><div className="marketing-hero-art"><img src={lightLogo} alt="Paideia Portals — Cultivating minds. Building futures."/><ProductComposition/></div></div></section>
  <section className="marketing-proof"><div className="marketing-shell"><p className="marketing-overline">THE PRODUCT, NOT A PROMISE</p><p>School work moves across people, academics and payments. Paideia brings those workflows into one school environment while giving each role a clearer place to work.</p></div></section>
  <section className="marketing-section"><div className="marketing-shell"><div className="marketing-section-intro"><p className="marketing-overline">WHY PAIDEIA</p><h2>Make the everyday work of school feel connected.</h2></div><div className="outcome-grid">{outcomes.map(([number, title, text]) => <article key={number}><span>{number}</span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section>
  <RoleShowcase/>
  <section className="marketing-section marketing-workflow"><div className="marketing-shell marketing-split"><div><p className="marketing-overline">ACADEMICS, IN CONTEXT</p><h2>From the school day to the report card.</h2><p>Attendance, score entry, results and timetable views sit alongside the people they support. Premium schools can add CBT exams and deeper performance tools.</p><Link className="marketing-text-link" to="/features">Explore academic workflows →</Link></div><div className="workflow-steps"><span>01 <strong>Record attendance</strong></span><span>02 <strong>Enter scores</strong></span><span>03 <strong>Review results</strong></span><span>04 <strong>Share role-specific views</strong></span></div></div></section>
  <section className="marketing-section marketing-payments"><div className="marketing-shell marketing-split"><div><p className="marketing-overline">SCHOOL FINANCE</p><h2>From fee setup to receipt.</h2><p>Schools can define fees, see outstanding balances and offer a verified online payment flow with receipts. Payment records remain tied to the right school.</p></div><div className="payment-sequence" aria-label="Fee payment workflow"><span>Set fees</span><b>→</b><span>Pay</span><b>→</b><span>Verify</span><b>→</b><span>Receipt</span></div></div></section>
  <section className="marketing-section marketing-custom"><div className="marketing-shell marketing-split"><div><p className="marketing-overline">DESIGNED AROUND YOUR SCHOOL</p><h2>Powered by Paideia. Presented as your school.</h2><p>School branding, colours and configured layouts make the portal feel at home in your community. The underlying workflows stay connected.</p><p className="marketing-small">The panels shown are design demonstrations, not customer schools.</p></div><div className="custom-visual"><div className="custom-swatch"><span>IDENTITY A</span><strong>Your school identity</strong><i/></div><div className="custom-swatch alternate"><span>IDENTITY B</span><strong>Your school identity</strong><i/></div></div></div></section>
  <section className="marketing-section marketing-steps"><div className="marketing-shell"><p className="marketing-overline">GETTING STARTED</p><h2>A considered start for every school.</h2><ol><li>Request a demo</li><li>Discuss your requirements</li><li>Configure your school portal</li><li>Onboard school users</li></ol></div></section>
  <section className="marketing-section marketing-closing"><div className="marketing-shell marketing-split"><div><p className="marketing-overline">CLEAR COMMERCIAL TERMS</p><h2>Start with what your school needs.</h2><p>Basic is ₦800 and Premium is ₦1,500 per active student per term. Schools with 100 or more active students receive an automatic 10% discount.</p><Link className="marketing-text-link" to="/pricing">Compare plans →</Link></div><div><p className="marketing-overline">BUILT WITH CARE</p><h3>Access that respects every role.</h3><p>School data is separated by tenant, account roles shape what people can access, and payments are verified before the portal records a successful transaction.</p></div></div></section>
  <section className="marketing-final-cta"><div className="marketing-shell"><p className="marketing-overline">LET'S BUILD YOUR SCHOOL'S DIGITAL HOME</p><h2>See Paideia in the context of your school.</h2><Link className="marketing-button marketing-button-light" to="/demo">Request a demo ↗</Link></div></section>
</Layout>; }

function Features() { return <Layout><section className="marketing-page-hero"><div className="marketing-shell"><p className="marketing-overline">THE PLATFORM</p><h1>Workflows that belong together.</h1><p>Paideia gives a school one configured place for the people, academic processes and financial tasks that make each term run.</p></div></section><RoleShowcase/><section className="marketing-section"><div className="marketing-shell feature-list">{outcomes.map(([number, title, text]) => <article key={number}><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></article>)}</div></section><section className="marketing-section marketing-premium"><div className="marketing-shell marketing-split"><div><p className="marketing-overline">PREMIUM CAPABILITIES</p><h2>More depth for schools ready to go further.</h2><p>Premium adds computer-based exams, question banks, analytics, bulk imports, promotion workflows and scratch cards to the Basic foundation.</p></div><div className="premium-list"><span>CBT & assessment</span><span>Performance analytics</span><span>Bulk student and staff imports</span><span>Promotion workflows</span></div></div></section><section className="marketing-final-cta"><div className="marketing-shell"><h2>See the platform around your school.</h2><Link className="marketing-button marketing-button-light" to="/demo">Request a demo ↗</Link></div></section></Layout>; }

function Pricing() { return <Layout><section className="marketing-page-hero"><div className="marketing-shell"><p className="marketing-overline">PRICING</p><h1>Clear plans for a connected school.</h1><p>Pricing is per active student, per term. Choose the capabilities your school needs.</p></div></section><section className="marketing-section"><div className="marketing-shell marketing-pricing-grid"><article><p className="marketing-overline">THE SCHOOL FOUNDATION</p><h2>Basic</h2><p className="marketing-price">₦800 <small>/ active student / term</small></p><p>School administration, attendance, results, fee management, receipts, timetables and notifications.</p><Link className="marketing-button" to="/demo">Request a demo ↗</Link></article><article className="pricing-premium"><p className="marketing-overline">MORE WAYS TO GROW</p><h2>Premium</h2><p className="marketing-price">₦1,500 <small>/ active student / term</small></p><p>Everything in Basic, plus CBT, analytics, bulk imports, promotion workflows and scratch cards.</p><Link className="marketing-button" to="/demo">Request a demo ↗</Link></article></div></section><section className="marketing-section marketing-pricing-note"><div className="marketing-shell marketing-split"><div><p className="marketing-overline">AUTOMATIC SCHOOL-SIZE DISCOUNT</p><h2>100+ active students? 10% off.</h2></div><p>The 10% discount applies automatically when a school has at least 100 active students. The current active-student count is used when the school starts its term checkout.</p></div></section></Layout>; }

function Demo() {
  const [form, setForm] = useState({ school_name: '', contact_name: '', email: '', phone: '', student_population: '', location: '', message: '', website: '' });
  const [status, setStatus] = useState(''); const [submitting, setSubmitting] = useState(false); const [sent, setSent] = useState(false);
  const update = event => setForm({ ...form, [event.target.name]: event.target.value });
  const submit = async event => { event.preventDefault(); if (form.website) return; setStatus(''); setSubmitting(true); try { await api.post('/api/demo-requests/', form); setSent(true); } catch (error) { const data = error.response?.data; setStatus(data?.detail || data?.error || 'Please review your details and try again.'); } finally { setSubmitting(false); } };
  return <Layout><section className="marketing-page-hero"><div className="marketing-shell"><p className="marketing-overline">A CONVERSATION ABOUT YOUR SCHOOL</p><h1>See what Paideia could look like for you.</h1><p>Tell us a little about your school. We’ll use it to shape a relevant product demonstration.</p></div></section><section className="marketing-section"><div className="marketing-shell marketing-demo-grid"><div className="demo-explainer"><h2>A useful first conversation.</h2><p>We’ll learn about your school, walk through relevant portal areas and discuss how your identity and workflows can be configured.</p><ol><li>Share your school’s details</li><li>Discuss the work you want to connect</li><li>See Paideia in context</li></ol><p>Already using Paideia? <Link to="/login">Access your portal</Link>.</p></div>{sent ? <div className="demo-confirmation" role="status"><span aria-hidden="true">✓</span><h2>Your request is with us.</h2><p>Thank you for telling us about your school. Your request has been recorded.</p><Link to="/features">Explore the platform →</Link></div> : <form className="marketing-demo-form" onSubmit={submit}><h2>Request a demo</h2><p>Fields marked * are required.</p><div className="demo-fields">{[['school_name', 'School name', 'text'], ['contact_name', 'Your name', 'text'], ['email', 'Work email', 'email'], ['phone', 'Phone number', 'tel'], ['student_population', 'Approximate active students', 'number'], ['location', 'Location', 'text']].map(([name, label, type]) => <label key={name}>{label} *<input name={name} type={type} required min={type === 'number' ? 1 : undefined} maxLength={type === 'tel' ? 30 : 255} value={form[name]} onChange={update}/></label>)}</div><label className="marketing-honeypot" aria-hidden="true">Website<input name="website" tabIndex="-1" autoComplete="off" value={form.website} onChange={update}/></label><label>What would you like to discuss?<textarea name="message" maxLength="2000" rows="4" value={form.message} onChange={update}/></label>{status && <p className="demo-error" role="alert">{status}</p>}<button className="marketing-button" disabled={submitting} type="submit">{submitting ? 'Sending…' : 'Send request ↗'}</button></form>}</div></section></Layout>;
}

function Contact() { return <Layout><section className="marketing-page-hero"><div className="marketing-shell"><p className="marketing-overline">CONTACT PAIDEIA</p><h1>Start with your school’s story.</h1><p>Tell us what your school is working toward. We’ll use your demo request to start the right conversation.</p><Actions/></div></section><section className="marketing-section"><div className="marketing-shell marketing-split"><h2>A more relevant conversation begins with context.</h2><p>Official direct contact details will appear here when the business confirms them. Until then, the demo form is the reliable way to reach the Paideia team.</p></div></section></Layout>; }

function Legal({ kind }) { const privacy = kind === 'privacy'; return <Layout><section className="marketing-page-hero"><div className="marketing-shell"><p className="marketing-overline">DRAFT FOR BUSINESS AND LEGAL REVIEW</p><h1>{privacy ? 'Privacy' : 'Terms of service'}</h1><p>This draft requires business and legal review before it becomes a final policy.</p></div></section><section className="marketing-section"><div className="marketing-shell marketing-legal"><h2>{privacy ? 'School and student information' : 'Using the service'}</h2><p>{privacy ? 'Paideia processes account, school and student information that schools provide to operate their portal. Schools are responsible for the information they enter and the people they authorize.' : 'Schools are responsible for their accounts, authorized users, acceptable use and subscription payments. Access may be limited or ended according to the agreed service arrangement.'}</p><h2>{privacy ? 'Access and retention' : 'Availability, payments and data'}</h2><p>{privacy ? 'Access is controlled through role-based accounts. Retention, support contacts, legal basis and data-request procedures require confirmation with the business and legal advisers.' : 'Service availability, billing, termination, data handling, limitations and support arrangements require confirmation in the school service agreement.'}</p></div></section></Layout>; }

export function MarketingPage({ page }) { return { home: <Home/>, features: <Features/>, pricing: <Pricing/>, demo: <Demo/>, contact: <Contact/>, privacy: <Legal kind="privacy"/>, terms: <Legal kind="terms"/> }[page]; }
